---
title: "Project Proposal"
author: "Namit Shrivastava"
format: pdf
editor: visual
---

For the SURVMETH 640 course's final project, I propose to build a predictive model that forecasts future transfer spending in the English Premier League for the next 20 seasons. My focus is solely on prediction i.e., developing a model that offers high accuracy for forward-looking expenditures rather than explaining the underlying relationships between spending and performance. The predictive insights from this model could empower club management to make more informed decisions regarding future transactions, such as setting competitive transfer budgets or deciding which players to pursue in anticipation of market trends. Using data from 1992/93 to 2021/22 scraped from Transfermarkt, I will leverage historical spending patterns to create a forecasting tool that serves as a practical decision-making aid.

In this project, I will also take a comprehensive approach by beginning with an exploratory data analysis that includes descriptive statistics and visualizations to highlight historical trends in transfer spending. Subsequently, I will experiment with a diverse set of supervised machine learning techniques such as time series methods like ARIMA and regression-based models like Random Forest, to identify the best approach for accurate forecasting. The ultimate objective for this project is to provide actionable predictions that have tangible benefits for team management like enabling clubs to strategically anticipate market conditions and optimize their financial planning for future transactions.
